name: Covid19Datasets
on:
  schedule:
    - cron: '00 14 * * *'
  workflow_dispatch:
jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - name: Pkg.add(PackageSpec(url="https://github.com/oem/Hamburg.jl")
        run: julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/oem/Hamburg.jl")'
      - name: Hamburg.Covid19.record()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia -e 'using Hamburg; Hamburg.Covid19.record()'
