name: DatasetUpdater
on:
  schedule:
    - cron: '00 14 * * *'
  workflow_dispatch:
jobs:
  DatasetUpdater:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
      - name: Install dependencies
        run: julia -e "using Pkg; Pkg.activate("."); Pkg.instantiate()"
      - name: Hamburg.Covid19.record()
        run: julia -e 'using Pkg; Pkg.activate("."); using Hamburg; Hamburg.Covid19.record()'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
