name: DatasetUpdater
on:
  schedule:
    - cron: '00 14 * * *'
  workflow_dispatch:
jobs:
  DatasetUpdater:
    runs-on: ubuntu-latest
    steps:
      - name: pkg"activate ."
        run: julia -e 'using Pkg; pkg"activate ."; using Hamburg; Hamburg.Covid19.record()'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
