name: DatasetUpdater
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
jobs:
  DatasetUpdater:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
      - name: Install dependencies
        run: julia -e 'using Pkg; Pkg.activate("."); Pkg.instantiate()'
      - name: Hamburg.Covid19.record()
        run: julia -e 'using Pkg; Pkg.activate("."); using Hamburg; Hamburg.Covid19.record()'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updates covid-19 datasets
