name: DatasetUpdater
on:
  schedule:
    - cron: '00 14 * * *'
  workflow_dispatch:
jobs:
  DatasetUpdater:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Hamburg.Covid19.record()
        run: julia -e 'using Pkg; Pkg.activate("."); Pkg.instantiate(); include("src/Hamburg.jl"); Hamburg.Covid19.record()'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
